# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.3

# compile C with /usr/bin/cc
C_DEFINES = -DCOMDARE_A03A_IS_ORIGINAL_CODEGEN=1 -DCOMDARE_A06_IS_ORIGINAL_CODEGEN=1 -DCOMDARE_CE_ENABLE_STATISTICS=1 -DCOMDARE_MEASUREMENT_ON=1

C_INCLUDES = -I/home/comdare/wt-ce-bump15/build/clang-debug/generated -I/home/comdare/wt-ce-bump15/libs/common/measurement/hdr_histogram_wrapper -I/home/comdare/wt-ce-bump15/libs/common/measurement/hdr_histogram_wrapper/vendor/include -I/home/comdare/wt-ce-bump15/libs/common/measurement/hdr_histogram_wrapper/vendor

C_FLAGS = -g

